### ISSUE TITLE
Paragraph block spacing not working

### ISSUE THREAD

**Issue by TheChilliPL** [Myriad-Dreamin/tinymist#706]
**Describe the bug**
Hey, so I have a very weird issue where
```typ
#show par: set block(spacing: 100pt)

Paragraph one blah blah blah

Paragraph two blah
```
doesn't seem to be working... 

It all ends up as
![image](https://github.com/user-attachments/assets/4b5fb64c-7237-43da-92b1-d5029da0625e)
no matter if the spacing is set to 0pt or 100pt.

I do not have any other block rules in my document or the template. It even doesn't work in a completely empty document (consisting just of the three lines above).

**Package/Software version:**

VSCode version(Help -> About):
```plain
Version: 1.95.0-insider (user setup)
Commit: 62a233cc87dc8d52a817739bc0d917089d4d103b
Date: 2024-10-17T05:09:34.012Z
Electron: 32.1.2
ElectronBuildId: 10323173
Chromium: 128.0.6613.162
Node.js: 20.17.0
V8: 12.8.374.33-electron.0
OS: Windows_NT x64 10.0.26040
```

tinymist extension version: `v0.11.33 (pre-release)`. Get it by `tinymist --version` in terminal.
No tinymist command found by the terminal. Found in VS Code extension list.

**Logs:**

tinymist server log(Output Panel -> tinymist):
```plain
[2024-10-17T22:43:36Z INFO  sync_lsp] handling workspace/executeCommand - (97) at Instant { t: 476414.83s }
[2024-10-17T22:43:36Z INFO  tinymist::actor::typ_client] the entry file of TypstActor(primary) is changing to EntryState { rooted: true, root: Some("f:\\Projects\\Typst\\msk-regulamin"), main: None }
[2024-10-17T22:43:36Z INFO  tinymist::cmd] file pinned: None
[2024-10-17T22:43:36Z INFO  sync_lsp] handled  workspace/executeCommand - (97) in 64.50µs
[2024-10-17T22:43:36Z INFO  tinymist::actor::typ_server] CompileServerActor: removing diag
[2024-10-17T22:43:36Z INFO  tinymist::actor::editor] received diagnostics from primary:13: diag(None)
[2024-10-17T22:43:36Z INFO  tinymist::actor::editor] received status request(primary) CompileSuccess
[2024-10-17T22:43:36Z INFO  sync_lsp] handling workspace/executeCommand - (98) at Instant { t: 476414.83s }
[2024-10-17T22:43:36Z INFO  tinymist::actor::preview] PreviewTask(bm2bep): killing
[2024-10-17T22:43:36Z INFO  tinymist::actor::preview] PreviewTask(bm2bep): wait for previewer to stop
[2024-10-17T22:43:36Z INFO  tinymist::tool::preview] Preview server joined
[2024-10-17T22:43:36Z INFO  typst_preview] Data plane server shutdown
[2024-10-17T22:43:36Z INFO  tinymist::tool::preview] graceful shutdown signal received
[2024-10-17T22:43:36Z INFO  typst_preview::actor::editor] EditorActor: received exit message
[2024-10-17T22:43:36Z INFO  tinymist::tool::preview] Gracefully shutdown!
[2024-10-17T22:43:36Z INFO  typst_preview::actor::editor] EditorActor: editor disconnected
[2024-10-17T22:43:36Z INFO  tinymist::actor::preview] PreviewTask(bm2bep): wait for static server to stop
[2024-10-17T22:43:36Z INFO  tinymist::tool::preview] PreviewTask(bm2bep): response channel closed
[2024-10-17T22:43:36Z INFO  tinymist::actor::preview] PreviewTask(bm2bep): killed
[2024-10-17T22:43:36Z INFO  sync_lsp] handled  workspace/executeCommand - (98) in 223.00µs
[2024-10-17T22:43:36Z INFO  typst_preview::actor::webview] WebviewActor: received unknown message from websocket: unsupported message Err(Error { err: ErrorImpl { loc: "cannot serve_with websocket", kind: None, arguments: [("err", "WebSocket protocol error: Sending after closing is not allowed")] } })
[2024-10-17T22:43:36Z INFO  typst_preview::actor::webview] WebviewActor: exiting
[2024-10-17T22:43:37Z INFO  sync_lsp] handling textDocument/documentColor - (99) at Instant { t: 476416.11s }
[2024-10-17T22:43:37Z INFO  sync_lsp] handled  textDocument/documentColor - (99) in 146.20µs
[2024-10-17T22:43:37Z INFO  sync_lsp] handling workspace/executeCommand - (100) at Instant { t: 476416.13s }
[2024-10-17T22:43:37Z INFO  tinymist::actor::typ_client] the entry file of TypstActor(primary) is changing to EntryState { rooted: true, root: Some("f:\\Projects\\Typst\\msk-regulamin"), main: Some(\main.typ) }
[2024-10-17T22:43:37Z INFO  tinymist::cmd] file focused: Some("f:\\Projects\\Typst\\msk-regulamin\\main.typ")
[2024-10-17T22:43:37Z INFO  sync_lsp] handled  workspace/executeCommand - (100) in 70.60µs
[2024-10-17T22:43:37Z INFO  tinymist::actor::editor] received status request(primary) Compiling
[2024-10-17T22:43:37Z INFO  sync_lsp] handling textDocument/codeAction - (101) at Instant { t: 476416.13s }
[2024-10-17T22:43:37Z INFO  sync_lsp] handled  textDocument/codeAction - (101) in 441.30µs
[2024-10-17T22:43:37Z INFO  tinymist::task::cache] CacheEvictTask: evict cache in 36.7µs
[2024-10-17T22:43:37Z INFO  tinymist::actor::editor] received diagnostics from primary:14: diag(Some(0))
[2024-10-17T22:43:37Z INFO  tinymist::actor::editor] received status request(primary) CompileSuccess
[2024-10-17T22:43:38Z INFO  sync_lsp] handling textDocument/foldingRange - (102) at Instant { t: 476416.36s }
[2024-10-17T22:43:38Z INFO  tinymist_query::syntax::lexical_hierarchy] lexical hierarchy analysis took 100.2µs
[2024-10-17T22:43:38Z INFO  sync_lsp] handled  textDocument/foldingRange - (102) in 197.20µs
[2024-10-17T22:43:38Z INFO  sync_lsp] handling textDocument/codeAction - (103) at Instant { t: 476416.37s }
[2024-10-17T22:43:38Z INFO  sync_lsp] handled  textDocument/codeAction - (103) in 147.10µs
[2024-10-17T22:43:38Z INFO  sync_lsp] handling textDocument/semanticTokens/full/delta - (104) at Instant { t: 476416.40s }
[2024-10-17T22:43:38Z INFO  sync_lsp] handled  textDocument/semanticTokens/full/delta - (104) in 291.70µs
[2024-10-17T22:43:38Z INFO  sync_lsp] handling textDocument/foldingRange - (105) at Instant { t: 476416.41s }
[2024-10-17T22:43:38Z INFO  tinymist_query::syntax::lexical_hierarchy] lexical hierarchy analysis took 105.2µs
[2024-10-17T22:43:38Z INFO  sync_lsp] handled  textDocument/foldingRange - (105) in 210.20µs
[2024-10-17T22:43:38Z INFO  sync_lsp] handling textDocument/codeLens - (106) at Instant { t: 476416.43s }
[2024-10-17T22:43:38Z INFO  sync_lsp] handled  textDocument/codeLens - (106) in 190.60µs
[2024-10-17T22:43:39Z INFO  sync_lsp] handling workspace/executeCommand - (107) at Instant { t: 476418.15s }
[2024-10-17T22:43:39Z INFO  tinymist::tool::preview] PreviewTask(fmw0mt): arguments: PreviewCliArgs {
        preview: PreviewArgs {
            enable_partial_rendering: true,
            invert_colors: "never",
            task_id: "fmw0mt",
            refresh_style: OnType,
        },
        compile: CompileOnceArgs {
            input: Some(
                "f:\\Projects\\Typst\\msk-regulamin\\main.typ",
            ),
            root: None,
            inputs: [],
            font: CompileFontArgs {
                font_paths: [],
                ignore_system_fonts: false,
            },
            creation_timestamp: None,
            certification: None,
        },
        preview_mode: Document,
        data_plane_host: "127.0.0.1:0",
        control_plane_host: "127.0.0.1:23626",
        static_file_host: "",
        not_as_primary: false,
        dont_open_in_browser: false,
    }
[2024-10-17T22:43:39Z INFO  typst_preview] Previewer: typst actor spawned
[2024-10-17T22:43:39Z INFO  typst_preview] Previewer: editor actor spawned
[2024-10-17T22:43:39Z DEBUG typst_preview::actor::typst] TypstActor: waiting for message
[2024-10-17T22:43:39Z INFO  tinymist::tool::preview] preview server listening on http://127.0.0.1:62516
[2024-10-17T22:43:39Z INFO  tinymist::tool::preview] PreviewTask(fmw0mt): preview server listening on: 127.0.0.1:62516
[2024-10-17T22:43:39Z INFO  sync_lsp] handled  workspace/executeCommand - (107) in 2.86ms
[2024-10-17T22:43:39Z INFO  tinymist::actor::editor] received status request(primary) Compiling
[2024-10-17T22:43:39Z INFO  tinymist::actor::editor] received diagnostics from primary:15: diag(Some(0))
[2024-10-17T22:43:39Z INFO  tinymist::actor::editor] received status request(primary) CompileSuccess
[2024-10-17T22:43:39Z INFO  tinymist::task::cache] CacheEvictTask: evict cache in 25µs
[2024-10-17T22:43:39Z INFO  sync_lsp] handling workspace/executeCommand - (108) at Instant { t: 476418.20s }
[2024-10-17T22:43:39Z INFO  sync_lsp] handled  workspace/executeCommand - (108) in 39.20µs
[2024-10-17T22:43:40Z DEBUG typst_preview::actor::render] OutlineRenderActor: waiting for message
[2024-10-17T22:43:40Z DEBUG typst_preview::actor::render] RenderActor: waiting for message
[2024-10-17T22:43:40Z DEBUG typst_preview::actor::render] RenderActor: has_full_render: true
[2024-10-17T22:43:40Z DEBUG typst_preview::actor::render] OutlineRenderActor: received message: RenderFullLatest
[2024-10-17T22:43:40Z DEBUG typst_preview::actor::render] OutlineRenderActor: sending outline
[2024-10-17T22:43:40Z DEBUG typst_preview::actor::render] OutlineRenderActor: waiting for message
[2024-10-17T22:43:40Z DEBUG typst_preview::actor::render] RenderActor: waiting for message
[2024-10-17T22:43:41Z INFO  sync_lsp] handling workspace/executeCommand - (109) at Instant { t: 476420.21s }
[2024-10-17T22:43:41Z INFO  sync_lsp] handled  workspace/executeCommand - (109) in 38.40µs
[2024-10-17T22:43:42Z INFO  sync_lsp] handling textDocument/codeLens - (110) at Instant { t: 476420.46s }
[2024-10-17T22:43:42Z INFO  sync_lsp] handled  textDocument/codeLens - (110) in 145.60µs
```

tinymist client log(Help -> Toggle Developer Tools -> Console):
```plain
log.ts:419  INFO Started local extension host with pid 23096.
log.ts:429  WARN [redhat.vscode-xml]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
log.ts:429  WARN [redhat.vscode-yaml]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope text.tex.
Old grammar file: file:///p%3A/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/latex/syntaxes/TeX.tmLanguage.json.
New grammar file: file:///c%3A/Users/Chilli/.vscode-insiders/extensions/james-yu.latex-workshop-10.5.4/syntax/TeX.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope text.tex.latex.
Old grammar file: file:///p%3A/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/latex/syntaxes/LaTeX.tmLanguage.json.
New grammar file: file:///c%3A/Users/Chilli/.vscode-insiders/extensions/james-yu.latex-workshop-10.5.4/syntax/LaTeX.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope text.bibtex.
Old grammar file: file:///p%3A/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/latex/syntaxes/Bibtex.tmLanguage.json.
New grammar file: file:///c%3A/Users/Chilli/.vscode-insiders/extensions/james-yu.latex-workshop-10.5.4/syntax/Bibtex.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope text.tex.markdown_latex_combined.
Old grammar file: file:///p%3A/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/latex/syntaxes/markdown-latex-combined.tmLanguage.json.
New grammar file: file:///c%3A/Users/Chilli/.vscode-insiders/extensions/james-yu.latex-workshop-10.5.4/syntax/markdown-latex-combined.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.cpp.embedded.latex.
Old grammar file: file:///p%3A/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/latex/syntaxes/cpp-grammar-bailout.tmLanguage.json.
New grammar file: file:///c%3A/Users/Chilli/.vscode-insiders/extensions/james-yu.latex-workshop-10.5.4/syntax/cpp-grammar-bailout.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.java.
Old grammar file: file:///p%3A/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/java/syntaxes/java.tmLanguage.json.
New grammar file: file:///c%3A/Users/Chilli/.vscode-insiders/extensions/redhat.java-1.35.1-win32-x64/language-support/java/java.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///p%3A/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///c%3A/Users/Chilli/.vscode-insiders/extensions/redhat.vscode-yaml-1.15.0/syntaxes/yaml.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.ignore.
Old grammar file: file:///p%3A/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/git-base/syntaxes/ignore.tmLanguage.json.
New grammar file: file:///c%3A/Users/Chilli/.vscode-insiders/extensions/syler.ignore-0.0.7/syntaxes/ignore.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.groovy.
Old grammar file: file:///p%3A/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/groovy/syntaxes/groovy.tmLanguage.json.
New grammar file: file:///c%3A/Users/Chilli/.vscode-insiders/extensions/vscjava.vscode-gradle-3.16.4/syntaxes/groovy.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope text.tex.
Old grammar file: file:///p%3A/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/latex/syntaxes/TeX.tmLanguage.json.
New grammar file: file:///c%3A/Users/Chilli/.vscode-insiders/extensions/james-yu.latex-workshop-10.5.4/syntax/TeX.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope text.tex.latex.
Old grammar file: file:///p%3A/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/latex/syntaxes/LaTeX.tmLanguage.json.
New grammar file: file:///c%3A/Users/Chilli/.vscode-insiders/extensions/james-yu.latex-workshop-10.5.4/syntax/LaTeX.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope text.bibtex.
Old grammar file: file:///p%3A/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/latex/syntaxes/Bibtex.tmLanguage.json.
New grammar file: file:///c%3A/Users/Chilli/.vscode-insiders/extensions/james-yu.latex-workshop-10.5.4/syntax/Bibtex.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope text.tex.markdown_latex_combined.
Old grammar file: file:///p%3A/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/latex/syntaxes/markdown-latex-combined.tmLanguage.json.
New grammar file: file:///c%3A/Users/Chilli/.vscode-insiders/extensions/james-yu.latex-workshop-10.5.4/syntax/markdown-latex-combined.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.cpp.embedded.latex.
Old grammar file: file:///p%3A/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/latex/syntaxes/cpp-grammar-bailout.tmLanguage.json.
New grammar file: file:///c%3A/Users/Chilli/.vscode-insiders/extensions/james-yu.latex-workshop-10.5.4/syntax/cpp-grammar-bailout.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.java.
Old grammar file: file:///p%3A/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/java/syntaxes/java.tmLanguage.json.
New grammar file: file:///c%3A/Users/Chilli/.vscode-insiders/extensions/redhat.java-1.35.1-win32-x64/language-support/java/java.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///p%3A/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///c%3A/Users/Chilli/.vscode-insiders/extensions/redhat.vscode-yaml-1.15.0/syntaxes/yaml.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.ignore.
Old grammar file: file:///p%3A/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/git-base/syntaxes/ignore.tmLanguage.json.
New grammar file: file:///c%3A/Users/Chilli/.vscode-insiders/extensions/syler.ignore-0.0.7/syntaxes/ignore.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.groovy.
Old grammar file: file:///p%3A/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/groovy/syntaxes/groovy.tmLanguage.json.
New grammar file: file:///c%3A/Users/Chilli/.vscode-insiders/extensions/vscjava.vscode-gradle-3.16.4/syntaxes/groovy.tmLanguage.json
register @ TMScopeRegistry.ts:46
console.ts:137 [Extension Host] determineVscodeTheme 2 (at console.<anonymous> (file:///p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:10031))
6An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
10console.ts:137 [Extension Host] determineVscodeTheme 2 (at console.<anonymous> (file:///p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:10031))
log.ts:419  INFO [perf] Render performance baseline is 30ms
log.ts:439   ERR [Extension Host] (node:23096) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code - Insiders --trace-deprecation ...` to show where the warning was created)
console.ts:137 [Extension Host] (node:23096) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code - Insiders --trace-deprecation ...` to show where the warning was created) (at file:///p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:10031)
Uqi @ console.ts:137
console.ts:137 [Extension Host] Preview Command f:\Projects\Typst\msk-regulamin\main.typ (at console.<anonymous> (file:///p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:10031))
console.ts:137 [Extension Host] Launched preview, data plane port:62196, static server port:62196 (at console.<anonymous> (file:///p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:10031))
2console.ts:137 [Extension Host] determineVscodeTheme 2 (at console.<anonymous> (file:///p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:10031))
log.ts:439   ERR MainThreadChatAgents2#$updateAgent: No agent with handle 1 registered
log.ts:439   ERR chatParticipant must be declared in package.json: github.copilot.editingSession: Error: chatParticipant must be declared in package.json: github.copilot.editingSession
    at UOt.$registerAgent (vscode-file://vscode-app/p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:610:31264)
    at Mht.S (vscode-file://vscode-app/p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3138:41686)
    at Mht.Q (vscode-file://vscode-app/p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3138:41464)
    at Mht.M (vscode-file://vscode-app/p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3138:40552)
    at Mht.L (vscode-file://vscode-app/p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3138:39789)
    at hZ.value (vscode-file://vscode-app/p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3138:38450)
    at x.B (vscode-file://vscode-app/p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:30:747)
    at x.fire (vscode-file://vscode-app/p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:30:965)
    at vW.fire (vscode-file://vscode-app/p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:644:10348)
    at l.onmessage (vscode-file://vscode-app/p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3149:11714)
console.ts:137 [Extension Host] [vscode-icons] v12.9.0 activated! (at console.<anonymous> (file:///p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:10031))
console.ts:137 [Extension Host] [relatedFiles] unknown language typst (at console.<anonymous> (file:///p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:10031))
Uqi @ console.ts:137
log.ts:439   ERR TreeError [DebugRepl] Tree input not set: Error: TreeError [DebugRepl] Tree input not set
    at ef.C (vscode-file://vscode-app/p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:412:30917)
    at ef.updateChildren (vscode-file://vscode-app/p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:412:30824)
    at hZ.value (vscode-file://vscode-app/p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2034:35241)
    at x.B (vscode-file://vscode-app/p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:30:747)
    at x.C (vscode-file://vscode-app/p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:30:817)
    at x.fire (vscode-file://vscode-app/p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:30:1034)
    at Dme.setVisible (vscode-file://vscode-app/p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:547:2794)
    at vscode-file://vscode-app/p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:662:11845
    at Array.map (<anonymous>)
    at Bh.setVisible (vscode-file://vscode-app/p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:662:11836)
78console.ts:137 [Extension Host] skip extension-output file extension-output-myriad-dreamin.tinymist-#1-Tinymist Typst Language Server (at console.<anonymous> (file:///p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:10031))
console.ts:137 [Extension Host] killed preview services (at console.<anonymous> (file:///p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:10031))
console.ts:137 [Extension Host] No dispose function found for task bm2bep (at console.<anonymous> (file:///p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:10031))
Uqi @ console.ts:137
console.ts:137 [Extension Host] Preview Command f:\Projects\Typst\msk-regulamin\main.typ (at console.<anonymous> (file:///p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:10031))
console.ts:137 [Extension Host] Launched preview, data plane port:62516, static server port:62516 (at console.<anonymous> (file:///p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:10031))
VM7:12 state eyJtb2RlIjoiZG9jIiwiYXNQcmltYXJ5IjpmYWxzZSwidXJpIjoiZmlsZTovLy9mJTNBL1Byb2plY3RzL1R5cHN0L21zay1yZWd1bGFtaW4vbWFpbi50eXAifQ==
VM7:16 vscode_state Object
VM8:5843 plugin initialized, build info: Object
VM8:5729 WebSocket connection opened WebSocket
VM8:5764 batch 2 messages
VM8:5785 recv partial-rendering 22
VM8:5822 Experimental feature: partial rendering enabled
VM8:5785 recv invert-colors 19
VM8:5828 Experimental feature: invert colors strategy taken: never
VM8:5764 batch 1 messages
VM8:5785 recv diff-v1 133540
VM8:1387 render_in_window with partial rendering enabled window 0.7450268951912546 -1430.4516387672088 -160.18078246611975 594.5314623626213 444.03602953398774 , patch scale 75154
VM8:368 parse 6.20 ms, rerender 9.10 ms, total 15.30 ms
VM8:1831 updateCanvas start
VM8:1863 updateCanvas one miss undefined c/cWU919XAqogUp6qwZVJhE
VM8:1863 updateCanvas one miss undefined cBzu6c8MftcMh49X77pzQhQ
VM8:1863 updateCanvas one miss undefined cEpXTXdgpkusqn8mhF2lhJQ
VM8:1871 updateCanvas done 53
VM8:1387 render_in_window with partial rendering enabled window 0.7621483375959079 -1463.3248081841432 826.9309462915601 608.1943734015346 454.2404092071611 , patch scale 161326
console.ts:137 [Extension Host] skip extension-output file extension-output-myriad-dreamin.tinymist-#1-Tinymist Typst Language Server (at console.<anonymous> (file:///p:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:10031))
VM8:368 parse 0.00 ms, rerender 23.30 ms, total 23.30 ms
VM8:1831 updateCanvas start
VM8:1871 updateCanvas done 4.300000011920929
```

**Additional context**

**Comment by Enter-tainer** [comment]
i believe it's not tinymist's fault. typst changes this in 0.12.0 and you might be using nightly tinymist

**Comment by TheChilliPL** [comment]
Huh, so should I use a different instruction for newer Typst? Couldn't find anything about it online

**Comment by TheChilliPL** [comment]
Oh, now par has a spacing property, that makes sense. Will check if it works fine and if so, I'll close the issue. Thanks so much!

**Comment by TheChilliPL** [comment]
It does work. Thanks again!
