### ISSUE TITLE
Error when opening `symbols` of package in sidebar

### ISSUE THREAD

**Issue by EpicEricEE** [Myriad-Dreamin/tinymist#718]
**Describe the bug**
When trying to open the `symbols` of any package in the sidebar (see image), an error occurs in the client log, and the symbols view remains empty.

```plain
TypeError: e.map is not a function
    at SS (c:\Users\...\.vscode\extensions\myriad-dreamin.tinymist-0.12.0-win32-x64\out\extension.js:67:7431)
    at vh.getPackageSymbols (c:\Users\...\.vscode\extensions\myriad-dreamin.tinymist-0.12.0-win32-x64\out\extension.js:67:4679)
    at vy.Y (/c:/Users/.../AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:13744)
    at vy.getChildren (/c:/Users/.../AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:10258)
```

![image](https://github.com/user-attachments/assets/344b924d-343d-44a9-99d4-7e2d1d3c1186)

**Package/Software version:**

tinymist extension version: `v0.12.0`.
```plain
tinymist 
Build Timestamp:     2024-10-19T17:14:35.214972600Z
Build Git Describe:  v0.12.0
Commit SHA:          4437b3bffb5f01f06bd64e4e424480ba72a88619
Commit Date:         None
Commit Branch:       None
Cargo Target Triple: x86_64-pc-windows-msvc
Typst Version:       0.12.0
```

**Comment by Myriad-Dreamin** [comment]
I changed the internal impls and broke it. I should add some fix along with testing.
