### ISSUE TITLE
"Export as Markdown" isn't working on VSCode

### ISSUE THREAD

**Issue by 6666dustry** [Myriad-Dreamin/tinymist#797]
**Describe the bug**
"Export as Markdown" does't work when typst document has functions.

**Package/Software version:**

VSCode version(Help -> About):
```plain
Version: 1.95.2 (user setup)
Commit: e8653663e8840adaf45af01eab5c627a5af81807
Date: 2024-11-07T11:07:22.054Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631
```

tinymist extension version: `v0.12.0`. Get it by `tinymist --version` in terminal.
```plain
// tinymist 
// Build Timestamp:     2024-03-22T02:18:18.207134800Z
// Build Git Describe:  v0.11.1-rc2-5-gf0a96cb-dirty
// Commit SHA:          f0a9...
// Commit Date:         None
// Commit Branch:       None
// Cargo Target Triple: x86_64-pc-windows-msvc
// Typst Version:       0.12.0
`tinymist --version` doesn't work, so I run `code tinymist --version` instead.
and I get:
1.95.2
e8653663e8840adaf45af01eab5c627a5af81807
x64

and my typst version is typst 0.12.0 (737895d7)
```

**Logs:**

tinymist server log(Output Panel -> tinymist):
```plain
[2024-11-12T07:34:36Z INFO  sync_lsp] handling textDocument/codeLens - (6430) at Instant { t: 2761049.72s }
[2024-11-12T07:34:36Z INFO  sync_lsp] handled  textDocument/codeLens - (6430) in 196.30µs
[2024-11-12T07:34:38Z INFO  sync_lsp] handling textDocument/codeAction - (6431) at Instant { t: 2761052.00s }
[2024-11-12T07:34:38Z INFO  sync_lsp] handled  textDocument/codeAction - (6431) in 181.60µs
[2024-11-12T07:34:42Z INFO  sync_lsp] handling workspace/executeCommand - (6432) at Instant { t: 2761056.27s }
[2024-11-12T07:34:42Z INFO  tinymist::task::export] RenderActor(Markdown): exporting EntryState { rooted: true, root: Some("d:\\report"), main: Some(\md-test.typ) } to "d:\\report\\md-test.md"
[2024-11-12T07:34:42Z INFO  sync_lsp] handled  workspace/executeCommand - (6432) in 590.50µs
[2024-11-12T07:34:42Z INFO  sync_lsp] handling textDocument/codeLens - (6433) at Instant { t: 2761056.35s }
[2024-11-12T07:34:43Z INFO  sync_lsp] handled  textDocument/codeLens - (6433) in 427.70µs
[2024-11-12T07:34:46Z INFO  sync_lsp] handling workspace/executeCommand - (6434) at Instant { t: 2761059.81s }
[2024-11-12T07:34:46Z INFO  tinymist::actor::typ_client] the entry file of TypstActor(primary) is changing to EntryState { rooted: true, root: Some("d:\\report"), main: None }
[2024-11-12T07:34:46Z INFO  tinymist::cmd] file focused: None
[2024-11-12T07:34:46Z INFO  sync_lsp] handled  workspace/executeCommand - (6434) in 66.40µs
[2024-11-12T07:34:46Z INFO  tinymist::actor::typ_server] CompileServerActor: removing diag
[2024-11-12T07:34:46Z INFO  tinymist::actor::editor] received diagnostics from primary:1248: diag(None)
[2024-11-12T07:34:46Z INFO  tinymist::actor::editor] received status request(primary) CompileSuccess
```

tinymist client log(Help -> Toggle Developer Tools -> Console):
```plain
sa: ファイル 'c:\Users\user\.vscode\extensions\hediet.vscode-drawio-1.6.6\drawio\src\main\webapp\js\croppie\croppie.min.css' を読み取れません (Error: 存在しないファイル 'c:\Users\user\.vscode\extensions\hediet.vscode-drawio-1.6.6\drawio\src\main\webapp\js\croppie\croppie.min.css' を解決できません)
    at Pnt.F (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3088:69694)
    at Pnt.D (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3088:69519)
    at async O2s (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3368:11158)
    at async Bat.zb (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3368:21812)
croppie.min.css:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
```

**Additional context**
typst code
```typ
= I am strong.
== I am strong too.
=== Am I strong?
I am the weakest.
#align(center)[
I am the center.
]
```
terminal log
```plain
Typst export task {
 "type": "typst",
 "command": "export",
 "export": {
  "format": "markdown"
 }
}
Exporting to markdown... {}
Typst export task failed: {
 "code": -32603,
 "message": "failed to convert to markdown: unknown variable: align",
 "stack": "Error: failed to convert to markdown: unknown variable: align\n    at bn (c:\\Users\\user\\.vscode\\extensions\\myriad-dreamin.tinymist-0.12.0-win32-x64\\out\\extension.js:6:228)\n    at An (c:\\Users\\user\\.vscode\\extensions\\myriad-dreamin.tinymist-0.12.0-win32-x64\\out\\extension.js:5:6250)\n    at Zn (c:\\Users\\user\\.vscode\\extensions\\myriad-dreamin.tinymist-0.12.0-win32-x64\\out\\extension.js:5:6387)\n    at Immediate.<anonymous> (c:\\Users\\user\\.vscode\\extensions\\myriad-dreamin.tinymist-0.12.0-win32-x64\\out\\extension.js:5:6137)\n    at processImmediate (node:internal/timers:483:21)",
 "error": {
  "code": -32603
 }
}
```

**Comment by Eric-Song-Nop** [comment]
In short, tinymist or typlite supports only a subset of typst when exporting to markdown sadly

**Comment by 6666dustry** [comment]
Oh, I didn't know that.

Then, I will try to find a way to convert pdf to markdown.

Thank you for providing information about my issue!

**Comment by Myriad-Dreamin** [comment]
Markdown export (typlite) is definitely lossy and limited by its syntax. So you might try to avoid using complex markup instead of finding some more powerful converter.

Due to lack of bandwidth, we might only focus on converting documentation in typst syntax to markdown for language service. Meanwhile, I'll be interested if anyone is going to discuss possibility to improve typlite for other usage.

Since this post is neither a real bug not an operatable feature request, I'll close it.
