### ISSUE TITLE
writing $med med arrow med med$ make the server crash

### ISSUE THREAD

**Issue by AliothCancer** [Myriad-Dreamin/tinymist#877]
**Describe the bug**
I made a function in which I used `$med med arrow med med$` that is the part of code why the server crashes, you can put anywhere not only in a function to trigger this crash. If you replace arrow with eta for example, the crash is not triggered.

**Package/Software version:**

VSCode version(Help -> About):
```plain
Version: 1.95.3
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:45:08.000Z
Electron: 31.7.5
ElectronBuildId: Electron for openSUSE
Chromium: 126.0.6478.234
Node.js: 20.18.0
V8: 12.6.228.30-electron.0
OS: Linux x64 6.11.8-1-default```

tinymist extension version: `v0.12.2`. Get it by `tinymist --version` in terminal.
I installed the vscode extension and I don't have the command tinymist available.
```plain
tinymist 
Build Timestamp:     
Build Git Describe:  
Commit SHA:          
Commit Date:        
Commit Branch:       
Cargo Target Triple: 
Typst Version:       typst 0.11.0 (e0d80968)
```

**Logs:**

tinymist server log(Output Panel -> tinymist):
```plain
[2024-11-21T08:50:52Z INFO  tinymist::actor::editor] received status request(primary) Compiling
thread '<unnamed>' panicked at /home/runner/.cargo/git/checkouts/typst-15b90983aa0184a9/58426a9/crates/typst/src/layout/inline/shaping.rs:605:45:
byte index 14 is not a char boundary; it is inside '\u{2069}' (bytes 12..15) of `· Q⁦￼  ⁩Litri/secondo
 · ⁦￼⁩⁦￼  ⁩mmHg
`
stack backtrace:
[2024-11-21T08:50:52Z INFO  sync_lsp] handling textDocument/documentColor - (4) at Instant { tv_sec: 264, tv_nsec: 389969582 }
[2024-11-21T08:50:52Z INFO  tinymist_query::analysis::global] analysis revision 9 is created
[2024-11-21T08:50:52Z INFO  sync_lsp] handled  textDocument/documentColor - (4) in 438.13µs
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::str::slice_error_fail_rt
   3: core::str::slice_error_fail
   4: typst::layout::inline::prepare::prepare
   5: typst::layout::inline::layout_inline
   6: typst::layout::flow::layout_flow
   7: typst::layout::pages::run::layout_page_run_impl
   8: typst::layout::pages::run::layout_page_run
   9: rayon::iter::plumbing::bridge_producer_consumer::helper
  10: rayon_core::join::join_context::{{closure}}
  11: rayon::iter::plumbing::bridge_producer_consumer::helper
  12: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  13: rayon_core::registry::WorkerThread::wait_until_cold
  14: rayon_core::registry::ThreadBuilder::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 09:50:52] Server process exited with signal SIGABRT.
[Info  - 09:50:52] Connection to server got closed. Server will restart.
true
```

**Additional context**

**Comment by Enter-tainer** [comment]
hi, could you please put the whold document here if possible? from the log, it looks like the panic  is not directly related to the math equation you mentioned here.

**Comment by AliothCancer** [comment]
```typst
#import "style.typ": apply_style
#import "custom_functions.typ": def


#let title = align(center)[
  #text(
    "Formulario di Dispositivi itps",
    30pt)
  
]

#let def(formula, unit) = {
  //set text(rgb("#000000"), 1em, weight: "bold")
  text(strong("· "), 1.4em, weight: "bold") + formula + $med med arrow med med$
  
  show text: set text(blue)
  show math.equation: set text(blue)
  unit + "\n" 
} 

#title
#apply_style[
#outline(indent: true)
#pagebreak()

= Valvole cardiache
== Effective Orifice Area (EOA)
  $
  "EOA" = 10^4/516 (Q) / (sqrt(Delta p))  arrow "cm"^2
  $
  #def[Q][Litri/secondo]
  #def[$Delta p$][mmHg]

== Discharge Coefficient (DC)
  $
  "DC" = "EOA"/A_"int" arrow ["adim."]
  $
  #param[EOA][$"cm"^2$]
  #param[$A_"interna"$][$"cm"^2$]
  
== Performance Index (PI)
  
  $
  "PI" = "EOA" / A_"est" arrow ["adim."]
  $

  #param[EOA][$"cm"^2$]
  #param[$A_"esterna"$][$"cm"^2$]    

#pagebreak()
== Reverse Flow (RF%)
  $
  "RF%" = V_"rigurgitato" / V_"eiettato" dot 100
  $
  \
  - $V_"rigurgitato" -- #block[È l'area negativa del grafico Portata-Tempo nel ventricolo sinistro.(Left-Ventricle)]$ \ \
  - $V_"eiettato" -- #block[È l'area positiva del grafico Portata-Tempo nel ventricolo sinistro (Left-Ventricle).]$ 

  == Numero di Reynolds (Re)

  $
  "Re" = (rho dot v dot d) / mu 
  $

  - $rho$ : densità sangue 1 $g/"cm"^3$

  - v: velocità del sangue $"cm"/s$

  - d: diametro del condotto $"cm"$

  - $mu$ : viscosità dinamica del sangue 0.03Poise = 0.03 $(g dot "cm") / s$
  \
  #strong("Nota:") Interpretazione del numero di Reynold  
  
  - Re < 2000 #h(2cm) $arrow$  flusso laminare
  - 2000 < Re < 4000 #h(.45cm)$arrow$  Regime di transizione
  - Re > 4000 #h(2cm) $arrow$ Regime turbolento
]
```

**Comment by AliothCancer** [comment]
oh actually it is not everywhere but only if it is in the style function

**Comment by Enter-tainer** [comment]
```
❯ typst compile test.typ
thread '<unnamed>' panicked at crates/typst/src/layout/inline/shaping.rs:605:45:
byte index 14 is not a char boundary; it is inside '\u{2069}' (bytes 12..15) of `· Q￼  Litri/secondo
 · ￼￼  mmHg
`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It is an upstream bug, unfortunately. Compiling your document with typst-cli also triggers crash.

**Comment by Enter-tainer** [comment]
```
#let def(formula, unit) = {
  formula + $med med arrow med med$
  unit + "\n" 
}
#def[$a$][]
```

Minimal example
